apiVersion: v1
kind: ReplicationController
metadata:
  name: jupyterhub
  labels:
    app: jupyterhub
spec:
  replicas: 1
  selector:
    name: jupyterhub
  template:
    metadata:
      labels:
        name: jupyterhub
    spec:
      containers:
      - name: jupyterhub
        image: docker.io/fluxcapacitor/jupyterhub
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: SPARK_MASTER
          value: spark://$(SPARK_MASTER_2_0_1_SERVICE_HOST):$(SPARK_MASTER_2_0_1_SERVICE_PORT_SPARK_SUBMIT)
        ports:
        - containerPort: 8754
