apiVersion: v1
kind: ReplicationController
metadata:
  name: jupyterhub-master
  labels:
    app: jupyterhub-master
spec:
  replicas: 1
  selector:
    name: jupyterhub-master
  template:
    metadata:
      labels:
        name: jupyterhub-master
    spec:
      containers:
      - name: jupyterhub-master
        image: docker.io/fluxcapacitor/jupyterhub
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: SPARK_MASTER
          value: "spark://$(MASTER_SPARK_2_0_1_SERVICE_HOST):$(MASTER_SPARK_2_0_1_SERVICE_PORT_SPARK_SUBMIT)"
        - name: SPARK_SUBMIT_ARGS
          value: "--conf spark.executor.cores=2 --conf spark.executor.memory=2g --packages com.amazonaws:aws-java-sdk:1.7.4,org.apache.hadoop:hadoop-aws:2.7.1 --jars /root/lib/jpmml-sparkml-package-1.0-SNAPSHOT.jar --py-files /root/lib/jpmml.py"
        - name: GITHUB_REPO 
          value: "http://github.com/fluxcapacitor/demos.ml"
        - name: SOURCE_ROOT_PATH 
          value: "demos.ml/jupyter"
        ports:
        - containerPort: 8754
