#!/bin/bash

cd ~
git clone --recursive -b $GITHUB_CLONE_BRANCH $GITHUB_REPO_OWNER_URL/$GITHUB_REPO_NAME.git

cd $GITHUB_REPO_NAME
git checkout -b $GITHUB_CHECKOUT_BRANCH
git reset --hard $GITHUB_RESET_REVISION

cd ~
ln -s $GITHUB_REPO_NAME/demos.ml/jupyter/notebooks notebooks
ln -s $GITHUB_REPO_NAME/demos.ml/jupyter/lib lib

cd ~
jupyterhub --config=config/jupyterhub_config.py
